In [1]:
# Sec A: Data Structures & Control Structure
#1.
list= [10,20,30,40,50]

#append:
list.append(60)
print("After Append: ",list)

#extend:
list.extend([70,80])
print("After Extend: ",list)

#insert:
list.insert(3,25)
print("After Insert: ",list)

#remove:
list.remove(50)
print("After Remove: ",list)

#pop
list.pop(3)
print("After Pop: ",list)

# index
print("Index of 30: ",list.index(30))

# count
print("Count of 20: ",list.count(20))

# sort
list.sort()
print("After Sort: ",list)

# reverse
list.reverse()
print("After Reverse: ",list)

#clear
list.clear()
print("After Clear: ",list)

After Append:  [10, 20, 30, 40, 50, 60]
After Extend:  [10, 20, 30, 40, 50, 60, 70, 80]
After Insert:  [10, 20, 30, 25, 40, 50, 60, 70, 80]
After Remove:  [10, 20, 30, 25, 40, 60, 70, 80]
After Pop:  [10, 20, 30, 40, 60, 70, 80]
Index of 30:  2
Count of 20:  1
After Sort:  [10, 20, 30, 40, 60, 70, 80]
After Reverse:  [80, 70, 60, 40, 30, 20, 10]
After Clear:  []


In [2]:
#2.
Students = ("Hitesh","Devanshu","Jayesh")
print(Students)
students[1] = "radha"
print(Students)

('Hitesh', 'Devanshu', 'Jayesh')


NameError: name 'students' is not defined

In [3]:
#3.
Set = {2,3,4,2,5,6,3,4,7,8,9}
print(Set)

{2, 3, 4, 5, 6, 7, 8, 9}


In [4]:
#4.
Person = {"name": "Hitesh", "age": 22, "City": "pune"}
Person["age"] = 22
Person["Email"] = "bokardehitesh@gmail.com"
print("Updated Dictionary: ", Person)

Updated Dictionary:  {'name': 'Hitesh', 'age': 22, 'City': 'pune', 'Email': 'bokardehitesh@gmail.com'}


In [5]:
#5.
age = int(input("Enter age: "))
if age>=18:
  print("You are eligible to vote")
else:
  print("You are not eligible to vote")

Enter age:  20


You are eligible to vote


In [6]:
#6.
marks = int(input("Enter marks obtained: "))

if marks >= 90:
    print("Grade A")
elif marks >= 75:
    print("Grade B")
elif marks >= 50:
    print("Grade C")
else:
    print("Fail")


Enter marks obtained:  92


Grade A


In [7]:
#7.
num = int(input("Enter the number: "))

if num > 0:
    if num % 2 == 0:
        print("Positive and Even")
    else:
        print("Positive but Odd")
elif num == 0:
    print("Zero")
else:
    print("Negative")


Enter the number:  7


Positive but Odd


In [8]:
#Section B: Numpy
#8.
import numpy as np

# Scalar
scalar = np.array(5)
print("Scalar: ",scalar)

# 1D array
arr1d = np.array([1, 2, 3, 4, 5])
print("1D Array: ",arr1d)

# 2D array
arr2d = np.arange(10, 70, 10).reshape(2, 3)
print("2D Array: ",arr2d)

Scalar:  5
1D Array:  [1 2 3 4 5]
2D Array:  [[10 20 30]
 [40 50 60]]


In [9]:
#9.
rand_arr = np.random.randint(0, 50, size=(4, 4))
print("Random Array: ",rand_arr)

Random Array:  [[16 44 43 18]
 [ 0 22 16 24]
 [25 46 39 27]
 [31 21 30 12]]


In [10]:
#10.
import pandas as pd
array_3x3 = np.arange(1, 10).reshape(3, 3)
df = pd.DataFrame(array_3x3, columns=['A', 'B', 'C'])
print(df)

   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9


In [11]:
#Section C: Exploring pandas

data = {
    "Name": ["soun", "monu", "mandar", "pratik", "pinku", "riya", "radha", "uma", "titu", "nitya"],
    "Age": [17, 21, 22, 23, 24, 25, 26, 27, 28, 29],
    "City": ["pune", "amt", "delhi", "nagpur", "chennai",
             "pune", "amt", "delhi", "nagpur", "chennai"],
    "Salary": [50500, 60500, None, 55500, 65500, None, 70500, 62500, 58500, 72500]
}

df = pd.DataFrame(data)
print(df)

#info and describe
print(df.info())

print(df.describe())

     Name  Age     City   Salary
0    soun   17     pune  50500.0
1    monu   21      amt  60500.0
2  mandar   22    delhi      NaN
3  pratik   23   nagpur  55500.0
4   pinku   24  chennai  65500.0
5    riya   25     pune      NaN
6   radha   26      amt  70500.0
7     uma   27    delhi  62500.0
8    titu   28   nagpur  58500.0
9   nitya   29  chennai  72500.0
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Name    10 non-null     object 
 1   Age     10 non-null     int64  
 2   City    10 non-null     object 
 3   Salary  8 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 452.0+ bytes
None
             Age        Salary
count  10.000000      8.000000
mean   24.200000  62000.000000
std     3.614784   7406.560798
min    17.000000  50500.000000
25%    22.250000  57750.000000
50%    24.500000  61500.000000
75%    26.750000  66750.0

In [12]:
#select column
print(df[["Name","City"]])

     Name     City
0    soun     pune
1    monu      amt
2  mandar    delhi
3  pratik   nagpur
4   pinku  chennai
5    riya     pune
6   radha      amt
7     uma    delhi
8    titu   nagpur
9   nitya  chennai


In [13]:
#Drop column
df = df.drop(columns=['City'])
print(df)

     Name  Age   Salary
0    soun   17  50500.0
1    monu   21  60500.0
2  mandar   22      NaN
3  pratik   23  55500.0
4   pinku   24  65500.0
5    riya   25      NaN
6   radha   26  70500.0
7     uma   27  62500.0
8    titu   28  58500.0
9   nitya   29  72500.0


In [14]:
#missing values with mean

df['Salary'].fillna(df['Salary'].mean(), inplace=True)
print(df)

     Name  Age   Salary
0    soun   17  50500.0
1    monu   21  60500.0
2  mandar   22  62000.0
3  pratik   23  55500.0
4   pinku   24  65500.0
5    riya   25  62000.0
6   radha   26  70500.0
7     uma   27  62500.0
8    titu   28  58500.0
9   nitya   29  72500.0


C:\Users\Lenovo\AppData\Local\Temp\ipykernel_10964\3399584236.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Salary'].fillna(df['Salary'].mean(), inplace=True)


In [15]:
#Remove Duplicates
df = df.drop_duplicates()
print(df)

     Name  Age   Salary
0    soun   17  50500.0
1    monu   21  60500.0
2  mandar   22  62000.0
3  pratik   23  55500.0
4   pinku   24  65500.0
5    riya   25  62000.0
6   radha   26  70500.0
7     uma   27  62500.0
8    titu   28  58500.0
9   nitya   29  72500.0
